version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6001:6001"
    depends_on:
      - mongo
    args:
      - API_PORT=6001
    environment:
      - API_PORT=6001
      - MONGO_URL=mongodb://mongo:27017/TodoList

  todolist:
    build:
      context: ./todolist
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:6001
    ports:
      - "3001:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:6001

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: